# These are supported funding model platforms

github: ['ANON-SYS', 'Core-Labs', 'thisismydesign']
patreon: ANONYMOUS
open_collective: ANONYMOUS
ko_fi: ANONYMOUS
community_bridge: ANONYMOUS
liberapay: ANONYMOUS
issuehunt: ANONYMOUS
otechie: ANONYMOUS
custom: ['BTC-ADDR：bc1qv3yuhsqhs2wjstjqj6va3z84pvrar8jkme3der', 'ETH-ADDR：0x4CA3002dfA8145d7C57486e61581A363680F277c', 'XMR-ADDR：4AjwE2amUShWWe7Y5NbVbHcCaRVbftubyaMgy69MRjSWMyGa5XUgnfaS7Bncu1Et3RCLASN1k4vG1a5raoJS4uhqMdPXXoe']