# These are supported funding model platforms

# Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
github: [ANON SYS, Core Labs]
# Replace with a single Patreon username
patreon: octocat
# Replace with a single Open Collective username
open_collective: ANON-SYS
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
# Replace with a single Community Bridge project-name e.g., cloud-foundry
community_bridge: Ethereum
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
otechie: # Replace with a single Otechie username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
custom: ['BTC: bc1qv3yuhsqhs2wjstjqj6va3z84pvrar8jkme3der', 'ETH: 0x4CA3002dfA8145d7C57486e61581A363680F277c', 'XMR: 4AjwE2amUShWWe7Y5NbVbHcCaRVbftubyaMgy69MRjSWMyGa5XUgnfaS7Bncu1Et3RCLASN1k4vG1a5raoJS4uhqMdPXXoe']