# anonymous-sys settings
title: ANON SYS
SEOTitle: "ANONYMOUS"
email: anon-sys@onion.org
description: WE ARE ANON SYS. WE ARE LEGION.
keyword: "ANONYMOUS"
locale: en-US
baseurl: ""
organization: "ANONYMOUS"
url: "https://anonymous-sys.github.io"
favicon: "/assets/resource/icon/favassets/icon-32x32.png"
twitter_username: sys
github_username:  sys
navs:
  -
    href: /
    label: Home
  -
    href: /activity
    label: Activity
  -
    href: /explore
    label: Explore
  -
    href: /enterprise
    label: Enterprise
  -
    href: /marketplace
    label: Marketplace

# Workload settings
workload_platform_(core):
  -
    href: /OpenAPI/Serverless/PaaS/Workload
    label: Workload

# NextWorldHub settings
nextworldhub_favicon: "/OpenAPI/Serverless/PaaS/NextWorldHub/assets/resource/icon/favicon.png"
nextworldhub_title: Next World Hub
nextworldhub_description: Anon Crypto Exchange Platform
nextworldhub_platform_(core):
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub
    label: Next World Hub
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Privatized/Error/404
    label: Error

nextworldhub_platform_(services):
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/Exchange/FluidExchange
    label: Fluid Exchange
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/Trade
    label: Trade
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/Chart
    label: Chart
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/Markets
    label: Markets
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/MatrixCloud/TechnicalAnalysis
    label: Technical Analysis
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/MatrixCloud/ForexCrossRates
    label: Forex Cross Rates
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/MatrixCloud/CompanyInfo
    label: Company Info
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Publicized/Services/MatrixCloud/ForexHeatMap
    label: Forex Heat Map

nextworldhub_platform_(actions):
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Privatized/Account/Settings
    label: Settings
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Privatized/Account/Profile
    label: Profile
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Privatized/Account/Wallets
    label: Wallets
  -
    href: /OpenAPI/Serverless/PaaS/NextWorldHub/Actions=Serverless/Reaction=Process/Privatized/Account/Locked
    label: Locked

backup_platform:
  -
    href: /OpenAPI/?Actions=Serverless&Platform=PaaS&Products=NextWorldHub/https://simpleicons.org/
    label: Next World Hub

# Build settings
theme: minima
plugins:
  - jekyll-feed


# Pagination
#paginate: 10
#paginate_path: 'page:num'
# bundle exec jekyll serve

 # Featured Tags
#featured-tags: true  
#featured-condition-size: 1     # A tag will be featured if the size of it is more than this condition value



# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
